variables:
  HELM_RELEASE: deploy
  SSH: 
stages:          
  # - build
  - deploy

# build_image:
#   stage: build
#   image:
#     name: gcr.io/kaniko-project/executor:v1.9.0-debug
#     entrypoint: [""]
#   script:
#     - /kaniko/executor
#       --context "${CI_PROJECT_DIR}/backend"
#       --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging")
    
.Deploy: &Deploy
  image: "dtzar/helm-kubectl:3.8.2"
  environment: 
    name: $ENV
  before_script:
    # !!!! Проблемы с таким подходом: при попытке выполнить запрос, например, kubectl get pods !reference 
    #  couldn't get current server API group list: Get "https://93.175.29.167:16443/api?timeout=32s": dial tcp 93.175.29.167:16443: i/o timeout !!!!
    # - kubectl config set-cluster k8s --server="${KUBE_API_SERVER}"
    # - kubectl config set clusters.k8s.certificate-authority-data ${KUBE_CA}
    # - kubectl config set-credentials gitlab --token="${KUBE_TOKEN}"
    # - kubectl config set-context default --cluster=k8s --user=gitlab
    # - kubectl config use-context default
    # - kubectl config set-context --current --namespace ${KUBERNETES_NAMESPACE}
    - helm template $HELM_RELEASE ${CI_PROJECT_DIR}/deploy 
      --debug 
    - apk add sshpass
    - mkdir -p ~/.ssh/
    - ssh-keyscan -t rsa kuber.atp-fivt.org  >> ~/.ssh/known_hosts
    - sshpass -p ${SERVER_PASSWORD} ssh ${SERVER_LOGIN}@kuber.atp-fivt.org echo ${KUBERNETES_NAMESPACE} >> /home/tpos2023a/tpos2023a175/test.txt
    - sshpass -p ${SERVER_PASSWORD} ssh ${SERVER_LOGIN}@kuber.atp-fivt.org kubectl --namespace ${KUBERNETES_NAMESPACE} delete  --ignore-not-found=true secret image-secret
    - sshpass -p ${SERVER_PASSWORD} ssh ${SERVER_LOGIN}@kuber.atp-fivt.org kubectl --namespace ${KUBERNETES_NAMESPACE} create secret docker-registry image-secret --docker-server=${CI_REGISTRY} --docker-username=${CI_DEPLOY_USER} --docker-password=${CI_DEPLOY_PASSWORD}
  script:
    - set -ex
    - echo "deploy" 

deploy_staging:
  <<: *Deploy
  stage: deploy
  variables:
    KUBERNETES_NAMESPACE: ${SERVER_LOGIN}
    ENV: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"

  


 

